title:             Mem learning
email:             zozon1330@gmail.com
description:       배운 것을 정리하는 공간 입니다.
author:            Hyemi Kim
# root 주소 (프로젝트명) ~> baseurl : "GHHM.github.io"
# netlify ~> baseurl : "/"
baseurl:           "/"
# 도메일 주소가 바뀌면 바꿔줘야한다. url: "https://ghhm.github.io/"
url:               "https://memlearning.netlify.com/"

# Social Profiles
twitter_username:  
github_username:   GHHM
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
  sass_dir: _sass