name: Mem Learning
author: memem
baseurl: /learning
description: theme for jekyll
github: http://www.github.com/GHHM
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: memem
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"

##Make sure to edit the above fields, especially for disqus.

search_enabled: true
highlighter: rouge
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
